font_family Maple Mono Regular

shell_integration no-cursor
cursor_shape beam

window_padding_width 7
window_padding_height 10

scrollback_lines 3000

font_size 12

background_opacity 1

background #19171c
foreground #8b8792

selection_background #585260
selection_foreground #e2dfe7

cursor #955ae7
cursor_text_color #19171c

color0 #19171c
color1 #be4678
color2 #2a9292
color3 #a06e3b
color4 #576ddb
color5 #955ae7
color6 #398bc6
color7 #8b8792

color8 #585260
color9 #d46a92
color10 #4ab0b0
color11 #c48a55
color12 #7b8fef
color13 #b07cf5
color14 #5aa5d6
color15 #e2dfe7
